#!/usr/bin/env node
/*
 * build-site.js — assemble the static GitHub Pages gallery into site/.
 *
 * GitHub Pages is static and can't list a directory at runtime, so we bake
 * every .song file into a manifest (site/songs.js) at build time. The page
 * then parses and plays them client-side with the SAME parser + engine the
 * rest of the project uses.
 *
 *   node tools/build-site.js        # writes ./site
 */
'use strict';

var fs = require('fs');
var path = require('path');
var MM = require('../src/song.js');

var ROOT = path.join(__dirname, '..');
var SONGS_DIR = path.join(ROOT, 'songs');
var OUT = path.join(ROOT, 'site');

function findSongs(dir) {
  var out = [];
  var entries = fs.readdirSync(dir, { withFileTypes: true });
  entries.sort(function (a, b) { return a.name < b.name ? -1 : 1; });
  for (var i = 0; i < entries.length; i++) {
    var full = path.join(dir, entries[i].name);
    if (entries[i].isDirectory()) out = out.concat(findSongs(full));
    else if (entries[i].name.endsWith('.song')) out.push(full);
  }
  return out;
}

// Fresh output dir.
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// Copy the shared parser + engine verbatim (one source of truth).
fs.copyFileSync(path.join(ROOT, 'src', 'song.js'), path.join(OUT, 'song.js'));
fs.copyFileSync(path.join(ROOT, 'src', 'engine.js'), path.join(OUT, 'engine.js'));

// Build the manifest, failing the build on any invalid song.
var files = fs.existsSync(SONGS_DIR) ? findSongs(SONGS_DIR) : [];
var manifest = [];
var invalid = 0;

for (var i = 0; i < files.length; i++) {
  var rel = path.relative(SONGS_DIR, files[i]);
  var source = fs.readFileSync(files[i], 'utf8');
  var song = MM.parseSong(source);
  if (song.errors.length) {
    invalid++;
    console.log('✗ ' + rel);
    for (var e = 0; e < song.errors.length; e++) console.log('    ' + song.errors[e]);
    continue;
  }
  manifest.push({ file: rel, source: source });
  console.log('✓ ' + rel + '  "' + song.title + '"');
}

if (invalid > 0) {
  console.error('\nBuild failed: ' + invalid + ' invalid song(s). Fix them before deploying.');
  process.exit(1);
}

fs.writeFileSync(
  path.join(OUT, 'songs.js'),
  '// Generated by tools/build-site.js — do not edit.\n' +
    'window.SONGS = ' + JSON.stringify(manifest, null, 2) + ';\n'
);

// Copy the gallery page as index.html.
fs.copyFileSync(path.join(__dirname, 'gallery.html'), path.join(OUT, 'index.html'));

console.log('\nBuilt ' + manifest.length + ' song(s) into site/');
